apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: padelgo
  MYSQL_USER: padelgo_user
  MYSQL_PASSWORD: padelgo_password
